2019-10-23 13:54:42,199 - __main__ - WARNING - Update "{'update_id': 278278821, 'message': {'message_id': 253, 'date': 1571838876, 'chat': {'id': 458632711, 'type': 'private', 'username': 'thorkelleinarsson', 'first_name': 'Þorkell'}, 'text': '/vedur a', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 6}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 458632711, 'first_name': 'Þorkell', 'is_bot': False, 'username': 'thorkelleinarsson', 'language_code': 'en'}}, '_effective_user': {'id': 458632711, 'first_name': 'Þorkell', 'is_bot': False, 'username': 'thorkelleinarsson', 'language_code': 'en'}, '_effective_chat': {'id': 458632711, 'type': 'private', 'username': 'thorkelleinarsson', 'first_name': 'Þorkell'}, '_effective_message': {'message_id': 253, 'date': 1571838876, 'chat': {'id': 458632711, 'type': 'private', 'username': 'thorkelleinarsson', 'first_name': 'Þorkell'}, 'text': '/vedur a', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 6}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 458632711, 'first_name': 'Þorkell', 'is_bot': False, 'username': 'thorkelleinarsson', 'language_code': 'en'}}}" caused error "name 'user' is not defined"
2019-10-23 13:54:45,867 - __main__ - WARNING - Update "{'update_id': 278278822, 'message': {'message_id': 255, 'date': 1571838885, 'chat': {'id': 458632711, 'type': 'private', 'username': 'thorkelleinarsson', 'first_name': 'Þorkell'}, 'text': '/vedur', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 6}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 458632711, 'first_name': 'Þorkell', 'is_bot': False, 'username': 'thorkelleinarsson', 'language_code': 'en'}}, '_effective_user': {'id': 458632711, 'first_name': 'Þorkell', 'is_bot': False, 'username': 'thorkelleinarsson', 'language_code': 'en'}, '_effective_chat': {'id': 458632711, 'type': 'private', 'username': 'thorkelleinarsson', 'first_name': 'Þorkell'}, '_effective_message': {'message_id': 255, 'date': 1571838885, 'chat': {'id': 458632711, 'type': 'private', 'username': 'thorkelleinarsson', 'first_name': 'Þorkell'}, 'text': '/vedur', 'entities': [{'type': 'bot_command', 'offset': 0, 'length': 6}], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 458632711, 'first_name': 'Þorkell', 'is_bot': False, 'username': 'thorkelleinarsson', 'language_code': 'en'}}}" caused error "name 'user' is not defined"
2019-10-23 13:55:49,619 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2019-10-23 13:55:49,858 - telegram.ext.updater - WARNING - Exiting immediately!
